name: "dev"
location: "[resourceGroup().location]"
storageAccountName: "[concat('spd', uniqueString(resourceGroup().id))]"
functionAppName: "[concat('spdfunction', uniqueString(resourceGroup().id))]"
serviceBusNamespace: "[concat('spdbus', uniqueString(resourceGroup().id))]"
sqlServerName: "[concat('spdsql', uniqueString(resourceGroup().id))]"
keyVaultName: "[concat('spdkeyvault', uniqueString(resourceGroup().id))]"
appInsightsName: "[concat('spdaip', uniqueString(resourceGroup().id))]"
documentIntelligenceResourceName: "[concat('spddi', uniqueString(resourceGroup().id))]"