benefit plan component
name "Test Pckg MD2 Rx2 Benefit Services"
description "Test Pckg MD2 Rx2 Benefit Services"
internal definition
in network tier definition
name "In Network"
benefits
benefit for service category "Abortion Procedures" is 100% of service cost deductible waived,
benefit for service category "Acupuncture" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Allergy Testing" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Applied Behavioral Analysis Therapy" is 100% of service cost with a copay of $80,
benefit for service category "Assistive Hearing Devices" is 100% of service cost with a copay of $80,
benefit for service category "Diagnostic Test (X-Ray And Blood Work)" is 100% of service cost deductible waived,
benefit for service category "Bariatric Surgery" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Breast Reconstruction (following a mastectomy)" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Pulmonary Rehab Therapy" is 60% of service cost,
benefit for service category "Cardiac Rehabilitation Services" is 60% of service cost,
benefit for service category "Chemotherapy" is 55% of service cost,
benefit for service category "Chiropractic services" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Cochlear Implants" is 60% of service cost,
benefit for service category "Maternity Inpatient Facility" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Diabetes Education" is 60% of service cost,
benefit for service category "Diabetic Equipment Supplies" is 100% of service cost with a copay of $80,
benefit for service category "Dialysis Treatments" is 60% of service cost with a copay of $100 per unit,
benefit for service category "Durable Medical Equipment" is 60% of service cost,
benefit for service category "Emergency Room Services" is 60% of service cost,
benefit for service category "Ambulance" is 60% of service cost with a copay of $250 per unit,
benefit for service category "Home Health Care/Nursing Services" is 60% of service cost,
benefit for service category "Hospice Care" is 100% of service cost with a copay of $80,
benefit for service category "Imaging (CT/PET Scans, MRIs) - Physician" is 60% of service cost,
benefit for service category "Infusion Therapy" is 100% of service cost with a copay of $80,
benefit for service category "Inpatient Facility Services" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Inpatient Physician Services" is 100% of service cost deductible waived,
benefit for service category "Inpatient Ancillary Services" is 60% of service cost,
benefit for service category "Inpatient Rehabilitation" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Lab Services" and supplier is contracted and supplier "AT_HS_S0001" is 100% of service cost with a copay of $50,
benefit for service category "Lab Services" and supplier is contracted is 60% of service cost,
benefit for service category "Maternity Inpatient Physician" is 100% of service cost deductible waived,
benefit for service category "Medical Supplies" is 60% of service cost,
benefit for service category "Mental Health & Substance Abuse Services Facility" is 100% of service cost with a copay of $100,
benefit for service category "Mental Health & Substance Abuse Services Physician" is 100% of service cost with a copay of $80,
benefit for service category "Office Visit - Primary Care" is 100% of service cost with a copay of $80,
benefit for service category "Outpatient Surgical Services" and supplier is contracted and supplier "AT_HS_S0001" is 65% of service cost,
benefit for service category "Outpatient Surgical Services" and supplier is contracted is 55% of service cost,
benefit for service category "Outpatient Rehabilitation Services" is 60% of service cost,
benefit for service category "Surgical Services (Professional)" is 60% of service cost,
benefit for service category "Pre-Admission Testing" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Prenatal and Postnatal Visits" is 100% of service cost deductible waived,
benefit for service category "Preventive Services" is 100% of service cost deductible waived,
benefit for service category "Injury or Illness" is 100% of service cost deductible waived until member receives 3 unit within calendar year then benefit is 100% of service cost with a copay of $40 per unit deductible waived until member receives 6 unit within calendar year then benefit is 60% of service cost,
benefit for service category "PREV Prostate Cancer Screening" is 100% of service cost deductible waived,
benefit for service category "Prosthetics" is 60% of service cost,
benefit for service category "Radiation Therapy" is 55% of service cost,
benefit for service category "Reconstructive Procedures/Potentially Cosmetic Procedures" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "PT/OT" is 60% of service cost,
benefit for service category "Speech Therapy" is 60% of service cost,
benefit for service category "Retail Health Clinic" is 100% of service cost with a copay of $80,
benefit for service category "Second Opinion" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Skilled Nursing Facility Services" is 60% of service cost,
benefit for service category "Office Visit - Specialty Care" is 60% of service cost with a copay of $200 per unit,
benefit for service category "Sterilization Services" is 100% of service cost deductible waived,
benefit for service category "Substance Abuse Inpatient Facility" is 100% of service cost with a copay of $100,
benefit for service category "Substance Abuse Outpatient Facility" is 100% of service cost with a copay of $80,
benefit for service category "Teladoc Services - Telemedicine" is 100% of service cost with a copay of $80,
benefit for service category "Transplant Services - Diagnosis" is 60% of service cost with a copay of $700 per confinement,
benefit for service category "Urgent Care Services" is 60% of service cost,
benefit for service category "Well-baby Care to Age 4" is 100% of service cost deductible waived,
benefit for service category "X-Ray (Professional)" is 60% of service cost
out of network tier definition
benefits
benefit for service category "Abortion Procedures" is 40% of service cost,
benefit for service category "Acupuncture" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Allergy Testing" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Applied Behavioral Analysis Therapy" is 40% of service cost,
benefit for service category "Assistive Hearing Devices" is 40% of service cost,
benefit for service category "Diagnostic Test (X-Ray And Blood Work)" is 40% of service cost,
benefit for service category "Bariatric Surgery" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Breast Reconstruction (following a mastectomy)" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Pulmonary Rehab Therapy" is 40% of service cost,
benefit for service category "Cardiac Rehabilitation Services" is 40% of service cost,
benefit for service category "Chemotherapy" is 35% of service cost,
benefit for service category "Chiropractic services" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Cochlear Implants" is 40% of service cost,
benefit for service category "Maternity Inpatient Facility" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Diabetes Education" is 40% of service cost,
benefit for service category "Diabetic Equipment Supplies" is 40% of service cost,
benefit for service category "Dialysis Treatments" is 40% of service cost with a copay of $150 per unit,
benefit for service category "Durable Medical Equipment" is 40% of service cost,
benefit for service category "Emergency Room Services" is 40% of service cost,
benefit for service category "Ambulance" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Home Health Care/Nursing Services" is 40% of service cost,
benefit for service category "Hospice Care" is 40% of service cost,
benefit for service category "Imaging (CT/PET Scans, MRIs) - Physician" is 40% of service cost,
benefit for service category "Infusion Therapy" is 40% of service cost,
benefit for service category "Inpatient Facility Services" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Inpatient Physician Services" is 40% of service cost,
benefit for service category "Inpatient Ancillary Services" is 40% of service cost,
benefit for service category "Inpatient Rehabilitation" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Lab Services" is 40% of service cost,
benefit for service category "Maternity Inpatient Physician" is 40% of service cost,
benefit for service category "Medical Supplies" is 40% of service cost,
benefit for service category "Mental Health & Substance Abuse Services Facility" is 100% of service cost with a copay of $200,
benefit for service category "Mental Health & Substance Abuse Services Physician" is 40% of service cost,
benefit for service category "Office Visit - Primary Care" is 40% of service cost,
benefit for service category "Outpatient Surgical Services" is 40% of service cost,
benefit for service category "Outpatient Rehabilitation Services" is 40% of service cost,
benefit for service category "Surgical Services (Professional)" is 40% of service cost,
benefit for service category "Pre-Admission Testing" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Prenatal and Postnatal Visits" is 40% of service cost,
benefit for service category "Preventive Services" is 40% of service cost,
benefit for service category "Injury or Illness" is 40% of service cost,
benefit for service category "PREV Prostate Cancer Screening" is 40% of service cost,
benefit for service category "Prosthetics" is 40% of service cost,
benefit for service category "Radiation Therapy" is 35% of service cost,
benefit for service category "Reconstructive Procedures/Potentially Cosmetic Procedures" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "PT/OT" is 40% of service cost,
benefit for service category "Speech Therapy" is 40% of service cost,
benefit for service category "Retail Health Clinic" is 40% of service cost,
benefit for service category "Second Opinion" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Skilled Nursing Facility Services" is 40% of service cost,
benefit for service category "Office Visit - Specialty Care" is 40% of service cost with a copay of $400 per unit,
benefit for service category "Sterilization Services" is 40% of service cost,
benefit for service category "Substance Abuse Inpatient Facility" is 100% of service cost with a copay of $200,
benefit for service category "Substance Abuse Outpatient Facility" is 40% of service cost,
benefit for service category "Teladoc Services - Telemedicine" is 40% of service cost,
benefit for service category "Transplant Services - Diagnosis" is 40% of service cost with a copay of $2100 per confinement,
benefit for service category "Urgent Care Services" is 40% of service cost,
benefit for service category "Well-baby Care to Age 4" is 40% of service cost,
benefit for service category "X-Ray (Professional)" is 40% of service cost
